## NLP Project 7: Hotel Review Analysis
## Problem Statement
A hotel management company collects customer reviews from booking websites and travel platforms to
understand guest experiences related to room quality, staff behavior, cleanliness, food service, and
amenities. Analyzing these reviews manually is challenging because of the large amount of feedback
received from customers. The company wants to apply NLP techniques to analyze guest reviews,
measure customer satisfaction, and identify areas that require service improvement.
## Tasks
1. Collect hotel review data.
2. Preprocess guest reviews.
3. Perform sentiment analysis.
4. Identify service-related issues.
5. Generate customer satisfaction report.

## Step 1: Import Libraries

In [32]:
import pandas as pd
import re
import nltk

nltk.download('stopwords')
nltk.download('vader_lexicon')

from nltk.corpus import stopwords
from nltk.sentiment import SentimentIntensityAnalyzer

from sklearn.feature_extraction.text import CountVectorizer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [33]:
reviews = [
    "The room was clean and comfortable.",
    "The staff were very friendly and helpful.",
    "The food was delicious.",
    "Excellent service and beautiful rooms.",
    "Very satisfied with my stay.",
    "The room was dirty.",
    "Food quality was poor.",
    "The staff were rude.",
    "The bathroom was not clean.",
    "Very disappointed with the service.",
    "Amazing breakfast and clean rooms.",
    "The hotel location was perfect.",
    "WiFi was very slow.",
    "Air conditioning was not working.",
    "The swimming pool was clean.",
    "Room service was excellent.",
    "The bed was uncomfortable.",
    "Parking was convenient.",
    "The check-in process was quick.",
    "Overall a wonderful experience."
]

df = pd.DataFrame({
    "Review": reviews
})

df.head()

                                      Review
0        The room was clean and comfortable.
1  The staff were very friendly and helpful.
2                    The food was delicious.
3     Excellent service and beautiful rooms.
4               Very satisfied with my stay.

## Step 2: Preprocess

In [34]:
stop_words = set(stopwords.words("english"))

def clean_text(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z ]','',text)

    words = text.split()

    words = [word for word in words if word not in stop_words]

    return " ".join(words)

df["Cleaned_Review"] = df["Review"].apply(clean_text)

df.head()

,Review,Cleaned_Review
0,The room was clean and comfortable.,room clean comfortable
1,The staff were very friendly and helpful.,staff friendly helpful
2,The food was delicious.,food delicious
3,Excellent service and beautiful rooms.,excellent service beautiful rooms
4,Very satisfied with my stay.,satisfied stay

## Step 3: Perform Sentiment Analysis

In [35]:
sia = SentimentIntensityAnalyzer()

def sentiment(text):

    score = sia.polarity_scores(text)["compound"]

    if score >= 0.05:
        return "Positive"

    elif score <= -0.05:
        return "Negative"

    else:
        return "Neutral"

df["Sentiment"] = df["Cleaned_Review"].apply(sentiment)

df

,Review,Cleaned_Review,Sentiment
0,The room was clean and comfortable.,room clean comfortable,Positive
1,The staff were very friendly and helpful.,staff friendly helpful,Positive
2,The food was delicious.,food delicious,Positive
3,Excellent service and beautiful rooms.,excellent service beautiful rooms,Positive
4,Very satisfied with my stay.,satisfied stay,Positive
5,The room was dirty.,room dirty,Negative
6,Food quality was poor.,food quality poor,Negative
7,The staff were rude.,staff rude,Negative
8,The bathroom was not clean.,bathroom clean,Positive
9,Very disappointed with the service.,disappointed service,Negative
10,Amazing breakfast and clean rooms.,amazing breakfast clean rooms,Positive
11,The hotel location was perfect.,hotel location perfect,Positive
12,WiFi was very slow.,wifi slow,Neutral
13,Air conditioning was not working.,air conditioning working,Neutral
14,The swimming pool was clean.,swimming pool clean,Positive
15,Room service was excellent.,room service excellent,Positive
16,The bed was uncomfortable.,bed uncomfortable,Negative
17,Parking was convenient.,parking convenient,Neutral
18,The check-in process was quick.,checkin process quick,Neutral
19,Overall a wonderful experience.,overall wonderful experience,Positive

In [36]:
vectorizer = CountVectorizer(stop_words="english")

X = vectorizer.fit_transform(df["Cleaned_Review"])

words = vectorizer.get_feature_names_out()

counts = X.sum(axis=0).A1

issue_df = pd.DataFrame({
    "Word": words,
    "Count": counts
})

issue_df = issue_df.sort_values(by="Count", ascending=False)

issue_df.head(10)

         Word  Count
7       clean      4
33    service      3
29       room      3
16       food      2
14  excellent      2
35      staff      2
30      rooms      2
2    bathroom      1
1     amazing      1
0         air      1

## Step 4: Generate Customer Satisfaction Report

In [37]:
report = df["Sentiment"].value_counts()

print("Customer Satisfaction Report")
print(report)

Customer Satisfaction Report
Sentiment
Positive    11
Negative     5
Neutral      4
Name: count, dtype: int64

In [38]:
print(df)

                                       Review  \
0         The room was clean and comfortable.
1   The staff were very friendly and helpful.
2                     The food was delicious.
3      Excellent service and beautiful rooms.
4                Very satisfied with my stay.
5                         The room was dirty.
6                      Food quality was poor.
7                        The staff were rude.
8                 The bathroom was not clean.
9         Very disappointed with the service.
10         Amazing breakfast and clean rooms.
11            The hotel location was perfect.
12                        WiFi was very slow.
13          Air conditioning was not working.
14               The swimming pool was clean.
15                Room service was excellent.
16                 The bed was uncomfortable.
17                    Parking was convenient.
18            The check-in process was quick.
19            Overall a wonderful experience.

                       Cleaned_Review Sentiment
0              room clean comfortable  Positive
1              staff friendly helpful  Positive
2                      food delicious  Positive
3   excellent service beautiful rooms  Positive
4                      satisfied stay  Positive
5                          room dirty  Negative
6                   food quality poor  Negative
7                          staff rude  Negative
8                      bathroom clean  Positive
9                disappointed service  Negative
10      amazing breakfast clean rooms  Positive
11             hotel location perfect  Positive
12                          wifi slow   Neutral
13           air conditioning working   Neutral
14                swimming pool clean  Positive
15             room service excellent  Positive
16                  bed uncomfortable  Negative
17                 parking convenient   Neutral
18              checkin process quick   Neutral
19       overall wonderful experience  Positive